name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Use Node.js 16
      run: |
        nvm install 16
        nvm use 16
      shell: bash

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy to GitHub Pages
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.name 'byaliego'
        git config --global user.email 'yigitogun@gmail.com'
        npm install -g gh-pages
        gh-pages -d build -u "byaliego" -r "ai_text_summarizer"
